CREATE TABLE IF NOT EXISTS `#__donations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `donor` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
